import type { NextPage } from 'next';
import Head from 'next/head';
import { AuthorIcon } from '../components/atom/AuthorIcon';
import { SelectBox } from '../components/atom/inputForm/SelectBox';
import { PrimaryLabel } from '../components/atom/label/PrimaryLabel';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PrimaryLabel>aaaaaaaaa</PrimaryLabel>

      <>
        <AuthorIcon iconUrl={'https://source.unsplash.com/random'} name='nakano'></AuthorIcon>
        <div className='flex items-center justify-between'>
          <h1 className='text-xl font-bold text-gray-700 md:text-2xl'>aaaaaaaaaa</h1>
          <SelectBox options={[{ value: 'Latest' }, { value: 'Last Week' }]} />
        </div>
      </>
    </div>
  );
};

export default Home;
