@startuml
card ユーザインターフェース
card アプリケーションサービス
card インフラ
note bottom
矢印は書いていないが
ユーザーインターフェイスと同階層として扱う
end note
card ドメインサービス
card ドメインモデル

ユーザインターフェース --> アプリケーションサービス
アプリケーションサービス --> ドメインサービス
ドメインサービス --> ドメインモデル
@enduml
