@startuml praha-challenge
actor 参加者
left to right direction
rectangle {
    参加者 -- (名前・メールアドレスを登録する)
    参加者 -- (課題の進捗ステータスを変更する)
    参加者 -- (在籍ステータスを変更する)
    参加者 -- (課題一覧を取得する)
    参加者 -- (課題の詳細を取得する)
    参加者 -- (ペア一覧を取得する)
    参加者 -- (ペア詳細を取得する)
    参加者 -- (チーム一覧を取得する)
    参加者 -- (チーム詳細を取得する)
}
@enduml
