@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Message" as Message {
  id: varchar<<PK>>
--
  text: varchar
  depth: integer
}

entity "MessageRelation" as MessageRelation {
  id: varchar<<PK>>
--
  message_id: varchar<<FK>>
  descendant_message_id: varchar<<FK>>
}

Message ||..o{ MessageRelation
Message ||..o{ MessageRelation
@enduml
