@startuml praha-challenge
skinparam PackageStyle rectangle

package チーム集約 {
    object チーム {
        チームID
        チーム名
    }
    object ペア {
        ペア名
        チームID
        List<参加者ID>
    }
}

package 参加者集約 {
    object 参加者 {
        参加者ID
        名前
        メールアドレス
    }
    object 在籍ステータス {
        ステータス名
    }
      object 課題進捗ステータス {
        課題ID
        ステータス名
    }
}

package 課題集約 {
    object 課題 {
        課題ID
        課題名
        課題内容
        メールアドレス
    }
  
}

note left of チーム
    * チーム名は数字でなければいけない
    * 名前は 3 文字以下でなければいけない
    * 最低でも参加者が 3 名いなければいけない
end note

note bottom of ペア
    * ペア名は半角英数字でなければいけない
    * ペア名は 1 文字でなければいけない
    * 参加者は 2 名〜3 名まで
end note

note bottom of 参加者
    * メールアドレスの重複は許容されない
    * ステータスが「在籍中」以外の場合、どのチームにもペアにも所属してはいけない
end note

note right of 在籍ステータス
    * 「在籍中」「休会中」「退会済」の 3 つのいずれか
    * パート2で脱落した候補者も以降、パート2キューブを獲得できない
end note

note top of 課題進捗ステータス
    * 「未着手」「レビュー待ち」「完了」の 3 つのいずれか
    * 一度「完了」にした進捗ステータスを「レビュー待ち」「未着手」に戻すことはできない
    * 進捗ステータスを変更できるのは、課題の所有者だけ
    * 課題（80 個ぐらい）を所有（割り当てられて）いる
end note


課題 "1" <-left- "1..n" 課題進捗ステータス
参加者 "1" *-up- "1" 課題進捗ステータス
在籍ステータス "1" -left-* "1" 参加者
参加者 "2..3" <-right- "1" ペア
チーム "1" *-down- "1..n" ペア

@enduml
